### ISSUE TITLE
PostPage for comments link is broken

### ISSUE THREAD

**Issue by Megha-Dev-19** [near/near-discovery-components#679] opened 2024-02-28 18:27 UTC
- copy any comment link on near.org
- [example](https://near.org/near/widget/PostPage?accountId=petersalomonsen.near&commentBlockHeight=113708336)

**Comment by shelegdmitriy** [comment] 2024-04-05 18:07
This issue is a duplicate of `#1` of this issue https://github.com/near/near-discovery/issues/909. I'm closing it as it's already solved

**Closed by shelegdmitriy** 2024-04-05 18:07 UTC
